In [2]:
# Step1
import numpy as np

In [5]:
# Step2
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
# Step3
C = np.dot(A, B)

In [8]:
# Step4
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [9]:
np.max(C)

47